### ISSUE TITLE
LICENCE ?

### ISSUE THREAD

**Issue by jrmgx** [pramjeet/peek-a-tab#13]
Hello, i'm wondering what licence the code is distributed with?

**Comment by pramjeet** [comment]
Hi @jrmgx, forgot to mention that but let's say you can do whatever you want with it :) I would appreciate if you will link back or mention, but that's just up to you.
 
Or you can contribute here itself and I will make a contributors page on peek-a-tab.org with both of our names (and other contributors in future).

**Comment by jrmgx** [comment]
Great, I will definitely link back to your work in a way or another!

**Comment by jrmgx** [comment]
FYI this is my plugin https://github.com/jrmgx/xplustab

**Comment by pramjeet** [comment]
@jrmgx Great!! Thanks for the mention!! :)
