### ISSUE TITLE
New version not opening window (+ solution)

### ISSUE THREAD

**Issue by Prid13** [pramjeet/peek-a-tab#14]
First of all, love your app!

Either the new Chrome update rendered your extension unable to open up for me, or it may be your new updated version of the extension. Either way, if I try to click or alt+space, the popup doesn't show up anymore.

I've used some time trying to debug the problem, and turns out, if I simply change the _title_ of the popup window from **Tabs you can peek at** to something else, or even delete/add a character, it magically works?!

**popup.js**

> popupWindow = window.open(
	browser.extension.getURL("app.html"),
	**"Tabs you can peek at",**
	"alwaysOnTop=yes,width=" + width + ",height=" + (win.height - 10) + ",left=" + window.screenLeft + ",top=" + (window.screenTop - 70)
);

Would appreciate if this gets fixed asap as I want to use the original extension instead of having a temp fix of my own which won't get updated. Or maybe I'm the only one with the problem?

**Comment by pramjeet** [comment]
Thanks @Prid13 for pointing out this. Will try to fix as soon as possible.

**Comment by pramjeet** [comment]
Sorry for the late reply @Prid13 , I think this issue is with the chrome browser. Reinstalling the extension fixes the issue.

**Comment by Prid13** [comment]
Thanks so much for following up, really appreciate it! Reinstalled and works like a charm, thanks :)

________________________________
Fra: Pramjeet Ahlawat <notifications@github.com>
Sendt: 30. juni 2017 12:52:08
Til: pramjeet/peek-a-tab
Kopi: Prid13; Mention
Emne: Re: [pramjeet/peek-a-tab] New version not opening window (+ solution) (#14)


Sorry for the late reply @Prid13<https://github.com/prid13> , I think this issue is with the chrome browser. Reinstalling the extension fixes the issue.
