### ISSUE TITLE
How can I custom the hot key (option + command)

### ISSUE THREAD

**Issue by yihuaxiang** [pramjeet/peek-a-tab#15]
I want to active the plugin by Command + E ,how can I make it ? thanks .

**Comment by pramjeet** [comment]
Sorry for late reply @yihuaxiang 
Yes, you can. There is no need to modify any code. Just go to extension management page on your browser by opening ```chrome://extensions/``` in url, and you will find the ```Keyboard shortcuts``` option at the bottom.

**Comment by ipstone** [comment]
Just a note the `Keyboard shortcuts` is at bottom left side - I have been looking for it elsewhere/everywhere! :)

**Comment by yihuaxiang** [comment]
> Sorry for late reply @yihuaxiang
> Yes, you can. There is no need to modify any code. Just go to extension management page on your browser by opening `chrome://extensions/` in url, and you will find the `Keyboard shortcuts` option at the bottom.

for new version chrome,open [chrome://extensions/shortcuts](chrome://extensions/shortcuts)
