### ISSUE TITLE
Feature request: close tabs with keyboard

### ISSUE THREAD

**Issue by ilyagr** [pramjeet/peek-a-tab#8]
I can already move up and down the list of tabs with the arrow keys. It would be great if I could press Del and/or Backspace to close the current tab.

Thanks (again) for the extension.

**Comment by pramjeet** [comment]
Hi @ilyagr, being super busy on my work project, I am not able to give time to peek-a-tab. So, things may take a while to implement. Apologies for that.

Thanks again to you too, I really appreciate your feedback.

**Comment by pramjeet** [comment]
Feature live in v1.5.4

**Comment by ilyagr** [comment]
Thank you, it works and is awesome. I also appreciate you fixing the bug
that used to make it difficult to move between windows via keyboard.

**Comment by pramjeet** [comment]
Thanks @ilyagr, yes.. the keyboard navigation thing was pretty messed up, but now it's done in a more standard way.
